services:
  app:
    container_name: crypto-microservice-totp
    image: crypto-microservice-totp-app
    build: .
    ports:
      - "8080:8080"
    volumes:
      - seed-data:/data
      - cron-output:/cron
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:
